name: $(BuildID)

trigger:
  batch: true
  branches:
    include:
    - fix/*
    - feat/*
    - main
  tags:
    include:
    - v*
  paths:
    exclude:
    - README.md

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    always: true
    branches:
      include:
      - main

variables:
- template: vars/global.yaml
- template: vars/dev.yaml

stages:

# Tests
# -----
- stage: TestStage
  displayName: Tests (Node.js)
  condition: eq(variables.isTag, 'False')
  jobs:
  - template: jobs/tests.yaml


